# Generated by Django 4.2.3 on 2023-09-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_registrotransaccion_monto_caja_del_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrotransaccion',
            name='monto_caja_del_dia',
        ),
    ]
