# Generated by Django 4.2.3 on 2023-09-03 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_registrotransaccion_monto_caja_del_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadre',
            name='fecha_hora_cierre',
        ),
        migrations.AddField(
            model_name='cuadre',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
