version: '3'

services:
  caja:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python app/manage.py makemigrations && python app/manage.py migrate && python app/manage.py migrate core && python app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - /dev/:/dev/
    ports:
      - "8000:8000"
    expose:
      - "8000"
    privileged: true
