services:
  caja:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python app/manage.py makemigrations && python app/manage.py migrate core && python app/manage.py migrate && python app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - /dev/:/dev/
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    privileged: true
    environment:
      - DJANGO_DEBUG=false

  frontend-dev:
    profiles: ["dev"]
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3005:3000"
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - caja

  frontend:
    profiles: ["prod"]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - caja

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: caja
      POSTGRES_DB: caja_registradora
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
