version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "echo 'hola' >> /dev/usb/lp0 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    privileged: true  # Agrega esta línea para dar acceso privilegiado al contenedor