services:
  caja:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python app/manage.py makemigrations && python app/manage.py migrate core && python app/manage.py migrate && python app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - /dev/:/dev/
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db  # Dependemos del servicio mariadb
    privileged: true

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: caja
      POSTGRES_DB: caja_registradora
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

