# Generated by Django 4.2.3 on 2023-10-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registrocajadiaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_venta',
            field=models.CharField(choices=[('unidad', 'Artículo por unidad'), ('gramaje', 'Artículo por gramaje'), ('valor', 'Articulo por valor')], default='unidad', max_length=10),
        ),
    ]
