# Generated by Django 4.2.5 on 2023-10-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_carritoitem_valor_alter_producto_tipo_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
