# Generated by Django 4.2.3 on 2023-08-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producto_tipo_gramaje_producto_tipo_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo_venta',
        ),
    ]
