# Generated by Django 4.2.3 on 2023-08-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_producto_tipo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='gramaje',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
