# Generated by Django 4.2.3 on 2023-08-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='tipo_gramaje',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogramos'), ('g', 'Gramos')], max_length=2, null=True),
        ),
    ]
