# Generated by Django 4.2.3 on 2023-08-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_carritoitem_gramaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='gramaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_gramaje',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('Ml', 'Mililitros'), ('L', 'Litros')], max_length=2, null=True),
        ),
    ]
