# Generated by Django 4.2.3 on 2023-08-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_configuracion_valor_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
