# Generated by Django 4.2.3 on 2023-08-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_configuracion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaproducto',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='gramaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
