# Generated by Django 4.2.3 on 2023-09-01 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_formapago'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTransaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_debito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_transferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
