# Generated by Django 4.2.3 on 2023-09-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_registrotransaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='registrotransaccion',
            name='valor_caja_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
