# Generated by Django 4.2.3 on 2023-09-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_cajadiaria_registrotransaccion_valor_caja_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajadiaria',
            name='retiro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cajadiaria',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
