# Generated by Django 4.2.3 on 2023-09-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_cuadre_fecha_hora_cierre_cuadre_fecha_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
        ),
    ]
