# Generated by Django 4.2.5 on 2023-09-10 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_actualizacionmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='permisos',
            field=models.CharField(default='Cajero', max_length=40, null=True, verbose_name='Permiso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Rut'),
        ),
        migrations.CreateModel(
            name='VentaEliminada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_eliminacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('productos_eliminados', models.TextField()),
                ('total_eliminado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario_eliminador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
