# Generated by Django 4.2.5 on 2023-09-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_usuario_permisos_alter_usuario_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='permisos',
            field=models.CharField(choices=[('cajero', 'Cajero'), ('admin', 'Administrador'), ('bodeguero', 'Bodeguero')], default='Cajero', max_length=40, null=True, verbose_name='Permiso'),
        ),
    ]
