# Generated by Django 4.2.3 on 2023-09-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_usuario_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaproducto',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.venta'),
        ),
    ]
