# Generated by Django 4.2.3 on 2023-09-10 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_ventaproducto_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaeliminada',
            name='productos_eliminados',
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta'),
        ),
        migrations.CreateModel(
            name='VentaEliminadaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('gramaje', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('venta_eliminada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ventaeliminada')),
            ],
        ),
        migrations.AddField(
            model_name='ventaeliminada',
            name='productos_eliminados',
            field=models.ManyToManyField(through='core.VentaEliminadaProducto', to='core.producto'),
        ),
    ]
