# Generated by Django 4.2.3 on 2023-09-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_ventaeliminada_productos_eliminados_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name_plural': 'Ventas'},
        ),
    ]
