# Generated by Django 4.2.3 on 2023-09-10 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_venta_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagoRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago_respaldo', to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='VentaProductoRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('gramaje', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('venta_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_respaldo', to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='VentaRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venta_original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='copia_respaldo', to='core.venta')),
            ],
        ),
        migrations.RemoveField(
            model_name='ventaeliminadaproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ventaeliminadaproducto',
            name='venta_eliminada',
        ),
        migrations.DeleteModel(
            name='VentaEliminada',
        ),
        migrations.DeleteModel(
            name='VentaEliminadaProducto',
        ),
    ]
