# Generated by Django 4.2.3 on 2023-09-10 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_formapagorespaldo_ventaproductorespaldo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaproductorespaldo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ventaproducto'),
        ),
    ]
