# Generated by Django 4.2.3 on 2023-09-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_ventaproductorespaldo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagorespaldo',
            name='venta_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago_respaldo', to='core.ventarespaldo'),
        ),
        migrations.AlterField(
            model_name='ventaproductorespaldo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='ventaproductorespaldo',
            name='venta_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_respaldo', to='core.ventarespaldo'),
        ),
    ]
