# Generated by Django 4.2.3 on 2023-09-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_formapagorespaldo_venta_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapagorespaldo',
            name='venta_original',
        ),
        migrations.RemoveField(
            model_name='ventaproductorespaldo',
            name='venta_original',
        ),
        migrations.RemoveField(
            model_name='ventarespaldo',
            name='venta_original',
        ),
        migrations.AddField(
            model_name='formapagorespaldo',
            name='venta_respaldo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ventarespaldo'),
        ),
        migrations.AddField(
            model_name='ventaproductorespaldo',
            name='venta_respaldo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ventarespaldo'),
        ),
    ]
