# Generated by Django 4.2.3 on 2023-09-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_formapagorespaldo_venta_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapagorespaldo',
            name='venta_respaldo',
        ),
        migrations.RemoveField(
            model_name='ventaproductorespaldo',
            name='venta_respaldo',
        ),
        migrations.AddField(
            model_name='formapagorespaldo',
            name='venta_respaldo_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventaproductorespaldo',
            name='venta_respaldo_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventarespaldo',
            name='venta_original_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
