# Generated by Django 4.2.3 on 2023-09-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_formapagorespaldo_venta_respaldo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapagorespaldo',
            name='venta_respaldo_id',
        ),
        migrations.RemoveField(
            model_name='ventaproductorespaldo',
            name='venta_respaldo_id',
        ),
        migrations.AddField(
            model_name='formapagorespaldo',
            name='venta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ventarespaldo'),
        ),
        migrations.AddField(
            model_name='ventaproductorespaldo',
            name='venta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ventarespaldo'),
        ),
    ]
