# Generated by Django 4.2.3 on 2023-09-10 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_formapagorespaldo_venta_respaldo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventarespaldo',
            name='fecha_anulacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
