# Generated by Django 4.2.3 on 2023-09-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_ventarespaldo_fecha_anulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave_anulacion',
            field=models.CharField(default='123', max_length=20),
        ),
    ]
