# Generated by Django 4.2.3 on 2023-10-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='tipo_venta',
            field=models.CharField(choices=[('1', 'No registrar Stock'), ('2', 'Registrar Stock con Descuento'), ('3', 'Registrar el stock de las ventas')], default='1', max_length=20),
        ),
    ]
