# Generated by Django 4.2.3 on 2023-10-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracion_tipo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='vuelto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
