# Generated by Django 4.2.5 on 2023-11-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_carritoitem_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacionmodel',
            name='version',
            field=models.CharField(default='version recién instalada', max_length=20),
        ),
    ]
