# Generated by Django 4.2.5 on 2023-11-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_actualizacionmodel_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='valor_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
