# Generated by Django 4.2.5 on 2023-11-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_producto_valor_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='separador',
            field=models.CharField(choices=[('1', '.'), ('2', ',')], default='1', max_length=20),
        ),
    ]
