# Generated by Django 4.2.5 on 2023-12-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_configuracion_separador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='separador',
            field=models.CharField(choices=[('1', 'Separar números por un < . > '), ('2', 'Separar números por un < , >')], default='1', max_length=20),
        ),
    ]
