# Generated by Django 4.2.5 on 2023-12-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_configuracion_separador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
