# Generated by Django 4.2.5 on 2023-12-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_carritoitem_valor_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoRapido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecla_rapida', models.CharField(max_length=10, unique=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
    ]
