# Generated by Django 4.2.5 on 2023-12-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_productorapido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorapido',
            name='tecla_rapida',
        ),
    ]
