# Generated by Django 4.2.3 on 2023-08-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_cantidad_alter_producto_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
