# Generated by Django 4.2.3 on 2023-08-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_gramaje',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogramos'), ('g', 'Gramos')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_venta',
            field=models.CharField(blank=True, choices=[('unidad', 'Artículo por unidad'), ('gramaje', 'Artículo por gramaje')], max_length=10, null=True),
        ),
    ]
