# Generated by Django 4.2.3 on 2023-08-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_producto_tipo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_venta',
            field=models.CharField(choices=[('unidad', 'Artículo por unidad'), ('gramaje', 'Artículo por gramaje')], default='unidad', max_length=10),
        ),
    ]
