# Generated by Django 4.2.3 on 2023-08-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_stock_tipo_gramaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='gramaje',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
