# Generated by Django 4.2.3 on 2023-09-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cajadiaria_retiro_alter_cajadiaria_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='tamano_letra',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
