# Generated by Django 4.2.3 on 2023-09-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_cuadre'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotransaccion',
            name='monto_caja_del_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registrotransaccion',
            name='monto_retiro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
