name: Auto Update

on:
  release:
    types:
      - published

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update project on VM
      run: |
        # Comandos para conectarte a la máquina virtual y actualizar el proyecto
        # Ejemplo (esto puede variar según tu configuración):
        
        # Conéctate a la máquina virtual por SSH
        ssh user@your-vm-ip-address "cd /path/to/your/project && git pull"

    # Aquí puedes agregar pasos adicionales según tus necesidades
